### ISSUE TITLE
[Feature Request] Invenio validation package should check existence of annotated data

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/arc-validate-package-registry#59]
Currently, the validation package only checks for the existence of top level metadata like Investigation description and Person E-Mail.

If I remember correctly, one requirement of the package was, that the existence of annotated data is checked. I.e. that the data file names used in assay and study Annotation tables have physical data counterparts in the ARC.

**Comment by kMutagene** [comment]
related: https://github.com/nfdi4plants/arc-validation-packages/issues/1

**Comment by omaus** [comment]
Closed via https://github.com/nfdi4plants/arc-validation-packages/pull/3.
